
jupyter:
  image: mnagaku/lc-minimal-notebook
  ports:
    - "8888:8888"
  command: bash -c "set +u ; . /usr/local/bin/start.sh jupyter notebook --NotebookApp.token=''"
  volumes:
    - .:/home/jovyan/openforum2018
    - /var/run/docker.sock:/var/run/docker.sock

3dwebmap:
  image: tumgis/3dcitydb-web-map
  ports:
    - "8000:8000"

drupal:
  image: drupal
  ports:
    - "80:80"

boinc:
  image: kyontan/boinc-runner
  environment:
    - PROJECT_URL=http://boinc.bakerlab.org/rosetta/
    - PROJECT_KEY=2005176_81e52362158f314bb416f6ef9ab3cd19
