version: '3'

services:

  jupyter:
    image: mnagaku/lc-minimal-notebook
    ports:
      - "8888:8888"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: bash -c "git clone --depth 1 https://github.com/mnagaku/openforum2018.git ; set +u ; . /usr/local/bin/start.sh jupyter notebook --NotebookApp.token=''"

  3dwebmap:
    image: tumgis/3dcitydb-web-map
    ports:
      - "8000:8000"

  wiki:
    image: realms/realms-wiki
    ports:
      - "5000:5000"

  boinc:
    image: kyontan/boinc-runner
    environment:
      - PROJECT_URL=http://boinc.bakerlab.org/rosetta/
      - PROJECT_KEY=2005176_81e52362158f314bb416f6ef9ab3cd19
